### ISSUE TITLE
Docker container having issue communicating to local server API

### ISSUE THREAD

**Issue by philipmac** [PrefectHQ/server#25] opened 2020-07-14 13:35 UTC
## Description

Attempting to use a Flow within Docker from 

https://docs.prefect.io/orchestration/tutorial/docker.html#persisting-your-flow-with-docker-storage

results in Flow going into Submitted state and appearing to stay there.

## Expected Behavior

Flow to complete run normally

## Reproduction

`prefect backend server`
`prefect server start`
`prefect agent start docker --show-flow-logs`

execute the hello-docker workflow (example given in tutorial - linked above)
Outputs:
https://gist.github.com/philipmac/3780609c3a69ca77881e9a9eef7fefdc

Use localhost:8080 to run workflow.

Examine outputs:
https://gist.github.com/philipmac/895d14feceda868e63be34f5953dd325

## Environment

```
$ prefect diagnostics
{
  "config_overrides": {
    "PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS": true,
    "PREFECT__FLOWS__CHECKPOINTING": true
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-40-generic-x86_64-with-glibc2.29",
    "prefect_version": "0.11.5",
    "python_version": "3.8.2"
  }
}
```

**Comment by philipmac** [comment] 2020-08-06 18:37
I updated Prefect:

```
$ prefect diagnostics
{
  "config_overrides": {
    "PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS": true,
    "PREFECT__FLOWS__CHECKPOINTING": true
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-42-generic-x86_64-with-glibc2.29",
    "prefect_version": "0.12.6",
    "python_version": "3.8.2"
  }
}
```
Started up Prefect (which unleashed untold fury on my terminal - but we'll ignore that), 

Checked localhost:8080, and... same problem. 

For the laugh I looked at localhost in Chrome (I default to using FF)... and everything works without issue. 

So, I guess that's the solution? Just use Chrome? 

There's nothing weird about my FF install, straight out of the Ubuntu apt repo, with Privacy Badger and uBlock Origin plug-ins installed. 

I'm not sure if you want to close this or not. I know that other people have seen this failure to connect with the graphql server, and using FF isn't completely unreasonable; however it does seems to work if you use Chrome.

**Comment by philipmac** [comment] 2020-08-07 16:30
Apologies, I lost track of which bug I was looking at. 

The bug that I posted originally, where the flow is submitted and gets stuck in Pending still exists. 

output of Agent:

https://gist.github.com/philipmac/023b4389a1399f3ffa883bd0a22105ec

**Comment by philipmac** [comment] 2020-08-07 16:51
Updated Prefect to version 0.13.1
```
$ prefect diagnostics
{
  "config_overrides": {
    "PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS": true,
    "PREFECT__FLOWS__CHECKPOINTING": true
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-42-generic-x86_64-with-glibc2.29",
    "prefect_version": "0.13.1",
    "python_version": "3.8.2"
  }
}
```



Attempted to run the docker tutorial from:

https://docs.prefect.io/orchestration/tutorial/docker.html#persisting-your-flow-with-docker-storage

gives:

```

Traceback (most recent call last):
  File "df.py", line 18, in <module>
    flow.register(project_name="Hello, World!")
  File "/home/macmenaminpe/.local/lib/python3.8/site-packages/prefect/core/flow.py", line 1579, in register
    registered_flow = client.register(
  File "/home/macmenaminpe/.local/lib/python3.8/site-packages/prefect/client/client.py", line 720, in register
    raise ValueError(
ValueError: Project Hello, World! not found. Run `client.create_project("Hello, World!")` to create it.
```

**Comment by philipmac** [comment] 2020-08-10 14:49
@znicholasbrown  -  were you able to replicate this issue with the dockerized flow timing out? (The initial issue reported.)

Did the pull req address this? If so can I test?

**Comment by znicholasbrown** [comment] 2020-08-10 15:05
@philipmac from the message you posted a few days ago, it looks like you'll need to create a project in your local Server; note that this is a change from the first version of Server, which didn't include projects.

**Comment by philipmac** [comment] 2020-08-10 15:54
@znicholasbrown  - Thanks - I added the project, registered the flow, and submitted a run via the web form. 

Same outcome, run appears to not start, no logs are found, and the run stays in "Pending" according to web GUI.

**Comment by philipmac** [comment] 2020-08-10 15:58
@znicholasbrown  to add, the container appears to be created. If I look at:

```
$ docker container ls 
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                            NAMES
c77ff4cd7485        hello-docker:2020-08-10t15-43-11-550907-00-00   "prefect execute clo…"   11 seconds ago      Up 10 seconds                                        clever_meitner
```

It's just that it does not connect with anything, and eventually times out and goes away.

**Comment by znicholasbrown** [comment] 2020-08-10 16:43
Hi @philipmac - can you provide the Docker output you're seeing? I'm not able to reproduce this issue locally. It's possible you'll need to upgrade the version of Core you're registering the flow with as well.

**Comment by leecheeaun** [comment] 2020-10-18 23:35
Getting the same error here - fresh install of Docker, docker-compose and Prefect on 20.04 Ubuntu DigitalOcean following @lauralorenz's reproduction instructions.

Also referenced the guide by @znicholasbrown [https://medium.com/the-prefect-blog/prefect-server-101-deploying-to-google-cloud-platform-47354b16afe2](url)

UI shows Connecting to http://localhost:4200/graphql, then Couldn't connect to http://localhost:4200/graphql

However, accessing at http://{MACHINE_PUBLIC_IP}:4200/graphql shows the graphql playground.

Have also added the path http://{MACHINE_PUBLIC_IP}:4200/graphql to ~/.prefect/config.toml, but no joy.

**Comment by rileyhun** [comment] 2020-11-18 17:29
Hello all, 

I am also experiencing this issue as well, where my docker container cannot connect to graphql. 

See error below:

```
[2020-11-18 01:25:04+0000] ERROR - prefect.CloudTaskRunner | Failed to set task state with error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='host.docker.internal', port=4200): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553cda2ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/conda/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f553cda2ac8>: Failed to establish a new connection: [Errno -2] Name or service not known
```

**Comment by joshmeek** [comment] 2020-11-19 22:14
@rileyhun Looks like it's an issue where the container that the agent is starting for the flow run is unable to communicate back to the server running on local host over `host.docker.internal`. What output do you see on your machine when you run this:

```python
from prefect.utilities.docker_util import get_docker_ip
print(get_docker_ip())
```

**Comment by rileyhun** [comment] 2020-11-19 22:44
> @rileyhun Looks like it's an issue where the container that the agent is starting for the flow run is unable to communicate back to the server running on local host over `host.docker.internal`. What output do you see on your machine when you run this:
> 
> ```python
> from prefect.utilities.docker_util import get_docker_ip
> print(get_docker_ip())
> ```

Hi @joshmeek, I'm getting the following output

```
>>> from prefect.utilities.docker_util import get_docker_ip
>>> print(get_docker_ip())
172.17.0.1
```

**Comment by znicholasbrown** [comment] 2021-01-22 18:45
It looks like some operating systems are preventing container - container communication which could be leading to this issue. For anyone running an OS with `firewalld`, you'll need to allow that communication and restart both firewalld and the docker service:
```
$ firewall-cmd --zone=public --add-masquerade --permanent
$ firewall-cmd --reload
$ systemctl restart docker
```

**Comment by philipmac** [comment] 2021-01-27 04:04
ok - this was related to firewall, in my case ufw
I followed the instructions given here:
https://stackoverflow.com/questions/30383845/what-is-the-best-practice-of-docker-ufw-under-ubuntu

starting with
 
> Solving UFW and Docker issues
> 
> This solution needs to modify only one UFW configuration file, all Docker configurations and options remain the default. Doesn't need to disable the docker iptables function.
> 
> Modify the UFW configuration file /etc/ufw/after.rules and add the following rules at the end of the file:...
> 
> 
> 

to fix I edited `/etc/ufw/after.rules`
adding
```
# BEGIN UFW AND DOCKER
*filter
:ufw-user-forward - [0:0]
:DOCKER-USER - [0:0]
-A DOCKER-USER -j RETURN -s 10.0.0.0/8
-A DOCKER-USER -j RETURN -s 172.16.0.0/12
-A DOCKER-USER -j RETURN -s 192.168.0.0/16
-A DOCKER-USER -j ufw-user-forward
-A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
-A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
-A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.16.0.0/12
-A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
-A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
-A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 172.16.0.0/12
-A DOCKER-USER -j RETURN
COMMIT
# END UFW AND DOCKER
```
I then ran
`ufw allow 4200`
restarted the agent, and it seems ok.

**Comment by leonarduschen** [comment] 2021-02-13 12:03
> Testing on a bone stock Ubuntu 18.04 EC2, allowing all traffic on all ports.
> 
> ran:
> 
> ```
> sudo apt update
> sudo apt install python3-pip install docker docker-compose
> pip3 install prefect
> sudo systemctl start  docker
> sudo usermod -aG docker $USER
> docker container run hello-world
> prefect backend server
> ```
> 
> Starting the server gives this:
> 
> ```
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
> Exception caught; killing services (press ctrl-C to force)
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/prefect/cli/server.py", line 317, in start
>     ["docker-compose", "pull"], cwd=compose_dir_path, env=env
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/bin/prefect", line 11, in <module>
>     sys.exit(cli())
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/prefect/cli/server.py", line 333, in start
>     ["docker-compose", "down"], cwd=compose_dir_path, env=env
>   File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 438, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 1.
> ```
> 
> Looks like we're going backwards here.

Hi I'm also getting the same error on Ubuntu 20.04

**Comment by madkinsz** [comment] 2021-02-16 15:46
@leonarduschen The solution to that error is outlined in https://github.com/PrefectHQ/server/issues/25#issuecomment-667145753 -- a docker-compose versioning issue. Please open a separate issue if you have continued problems as this issue is for communication problems.

**Comment by benwhale** [comment] 2021-06-28 15:47
Hi all, I appear to be getting the same issue.

### Reproduction

```
prefect backend server
prefect server start
prefect agent start docker --show-flow-logs
prefect create project 'tutorial'
```
### Environment
Ubuntu 20.04.2 LTS
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-77-generic-x86_64-with-glibc2.29",
    "prefect_backend": "server",
    "prefect_version": "0.14.21",
    "python_version": "3.8.5"
  }
}
```


I'm running a modified version of the basic prefect hello-flow tutorial to use docker.

```
import os
import time

import prefect
from prefect import task, Flow, Parameter
from prefect.run_configs import DockerRun
from prefect.executors import LocalDaskExecutor
from prefect.storage import Docker


@task
def say_hello(name):
    # Add a sleep to simulate some long-running task
    time.sleep(10)
    # Load the greeting to use from an environment variable
    greeting = os.environ.get("GREETING")
    logger = prefect.context.get("logger")
    logger.info(f"{greeting}, {name}!")


with Flow("hello-flow", storage=Docker(image_name="say_hello")) as flow:
    people = Parameter("people", default=["Arthur", "Ford", "Marvin"])
    say_hello.map(people)

# Configure the `GREETING` environment variable for this flow
flow.run_config = DockerRun(env={"GREETING": "Hello"})

# Use a `LocalDaskExecutor` to run this flow
# This will run tasks in a thread pool, allowing for parallel execution
flow.executor = LocalDaskExecutor()

# Register the flow under the "tutorial" project
flow.register(project_name="tutorial")
```
When executed, I am getting a user warning for no result handler and no registry url (my understanding is this shouldn't impact the underlying issue), and my docker image is built

```
Step 1/9 : FROM prefecthq/prefect:0.14.21-python3.8
 ---> 26097bbc43fe
Step 2/9 : ENV PREFECT__USER_CONFIG_PATH='/opt/prefect/config.toml'
 ---> Using cache
 ---> 8efaaaadb00a
Step 3/9 : RUN pip install pip --upgrade
 ---> Using cache
 ---> ab78a59cac20
Step 4/9 : RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@0.14.21#egg=prefect[all_orchestration_extras]
 ---> Using cache
 ---> 94043b606717
Step 5/9 : RUN pip install wheel
 ---> Using cache
 ---> 1aa4927c5324
Step 6/9 : RUN mkdir -p /opt/prefect/
 ---> Using cache
 ---> a053665dc619
Step 7/9 : COPY hello-flow.flow /opt/prefect/flows/hello-flow.prefect
 ---> 28770d6f7b98
Step 8/9 : COPY healthcheck.py /opt/prefect/healthcheck.py
 ---> e38f8835afc3
Step 9/9 : RUN python /opt/prefect/healthcheck.py '["/opt/prefect/flows/hello-flow.prefect"]' '(3, 8)'
 ---> Running in a72182b9dd29
Beginning health checks...
System Version check: OK
Cloudpickle serialization check: OK
Result check: OK
Environment dependency check: OK
All health checks passed.
 ---> 5a608b30ef77
Successfully built 5a608b30ef77
Successfully tagged say_hello:2021-06-28t15-33-29-484772-00-00
Flow URL: http://localhost:8080/default/flow/0c9b5fd7-098f-43d7-b0d9-784288f7193d
 └── ID: be95c6ea-00ad-431d-944b-ff3843ec3482
 └── Project: tutorial
 └── Labels: []

Process finished with exit code 0
```
Docker agent is visible in the local UI, and hello-flow shows up in the tutorial project.

Clicking on the quick run results in the task getting to submitted status, but the agent spits out the familiar error message referencing Name or service not known, and ultimately hitting host.docker.internal:4200 and giving an error about max retries to /graphql given a failure to establish a new collection. (below)
```
[2021-06-28 15:37:43,468] INFO - agent | Registering agent...
[2021-06-28 15:37:43,503] INFO - agent | Registration successful!

 ____            __           _        _                    _
|  _ \ _ __ ___ / _| ___  ___| |_     / \   __ _  ___ _ __ | |_
| |_) | '__/ _ \ |_ / _ \/ __| __|   / _ \ / _` |/ _ \ '_ \| __|
|  __/| | |  __/  _|  __/ (__| |_   / ___ \ (_| |  __/ | | | |_
|_|   |_|  \___|_|  \___|\___|\__| /_/   \_\__, |\___|_| |_|\__|
                                           |___/

[2021-06-28 15:37:43,512] INFO - agent | Starting DockerAgent with labels []
[2021-06-28 15:37:43,512] INFO - agent | Agent documentation can be found at https://docs.prefect.io/orchestration/
[2021-06-28 15:37:43,512] INFO - agent | Waiting for flow runs...
[2021-06-28 15:39:39,489] INFO - agent | Deploying flow run ce2a1809-f004-44d6-89c0-65dd3e899868 to execution environment...
[2021-06-28 15:39:39,848] INFO - agent | Completed deployment of flow run ce2a1809-f004-44d6-89c0-65dd3e899868
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f859038e580>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=4200): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f859038e580>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/cli/execute.py", line 49, in flow_run
    result = client.graphql(query)
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 298, in graphql
    result = self.post(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 213, in post
    response = self._request(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 459, in _request
    response = self._send_request(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 351, in _send_request
    response = session.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=4200): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f859038e580>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

host.docker.internal doesn't resolve to localhost on the host by default in docker for linux. I can't really do any hacks around adding extra hosts manually as we'd need to be able to deploy this.

Help would be appreciated!

**Comment by madkinsz** [comment] 2021-06-28 19:19
Hi @benwhale -- it looks like you're encountering a (now Ubuntu specific) error as described in https://github.com/PrefectHQ/prefect/issues/2324

https://github.com/PrefectHQ/prefect/issues/2324#issuecomment-613351789 will fix this. 

I continue to be confused that this is affecting people since it should be resolved by https://github.com/moby/moby/pull/40007 -- can you confirm you are on a new version of docker? I removed our workaround that was implemented while we waited for that to be in the mainstream in https://github.com/PrefectHQ/prefect/pull/4446. The removal of the workaround was released in 0.14.18 so you could also downgrade to 0.14.17 to resolve this in the meantime if the comment linked above does not resolve this for you.

**Comment by benwhale** [comment] 2021-06-29 12:10
HI @madkinsz, thanks for the quick reply! Rolling back the version to 0.14.17 has worked. I reinstalled docker yesterday, so should be pretty cutting edge version wise. We'd ideally want to deploy without needing to play with the docker host in the environment, so will rely on the rollback for now, as I was not sure if there was a way to pass that flag to the docker commands prefect is running under the hood?

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`
```
It looks like the merged moby PR gives an additional flag to run individual containers `docker run --add-host host.docker.internal:host-gateway`, rather than the host.docker.internal being available by default as in Docker Desktop for Win/Mac. https://github.com/moby/moby/pull/40007#issuecomment-578729356

I followed this https://github.com/docker/for-linux/issues/264#issuecomment-829328185 comment to run an alpine image with that manual binding and got the expected response showing it bound when that flag was used
```
$ docker run --rm --add-host host.docker.internal:host-gateway alpine cat /etc/hosts
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
5843afab3874: Pull complete 
Digest: sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0
Status: Downloaded newer image for alpine:latest
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.1      host.docker.internal
172.17.0.2      692fded4d92b
```

**Comment by madkinsz** [comment] 2021-06-29 14:08
Ah I misunderstood the moby PR -- thanks for taking a look at that. I've opened a PR at https://github.com/PrefectHQ/prefect/pull/4714 if you want to give it a try (note this branches off of the 0.15.0 pre-release though). I'll test it this week and make sure this works without breaking anything else.

**Closed** 2021-07-23 00:05 UTC

**Comment by philipmac** [comment] 2021-08-05 17:56
@madkinsz 

Just tested this:

```
[2021-08-05 15:59:00,596] ERROR - agent | Exception encountered while deploying flow run 17a485e4-44e6-44bb-af9a-6c5b196910a7
Traceback (most recent call last):
  File "/home/uname/.local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.40/containers/create?name=economic-crow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uname/.local/lib/python3.8/site-packages/prefect/agent/agent.py", line 391, in _deploy_flow_run
    deployment_info = self.deploy_flow(flow_run)
  File "/home/uname/.local/lib/python3.8/site-packages/prefect/agent/docker/agent.py", line 453, in deploy_flow
    container = self.docker_client.create_container(
  File "/home/uname/.local/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/uname/.local/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/uname/.local/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/uname/.local/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/uname/.local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("invalid IP address in add-host: "host-gateway"")
```

**Comment by madkinsz** [comment] 2021-08-05 21:00
Hey @philipmac -- this means that your docker version is below our minimum required version. See https://github.com/PrefectHQ/prefect/pull/4772. You can use https://github.com/PrefectHQ/prefect/pull/4777 to override this value. 

See also https://github.com/PrefectHQ/prefect/pull/4809

**Comment by philipmac** [comment] 2021-08-06 12:05
Got it, that's working. Thanks @madkinsz !

**Comment by weisiang9678** [comment] 2021-09-13 12:47
[https://github.com/PrefectHQ/server/issues/25#issuecomment-765613421](This suggestion solved my problem ! I was unable to connect to the Prefect server at 127.0.0.1:4200/graphql before i try the doing the suggestions)

**Comment by weisiang9678** [comment] 2021-09-13 12:49
@znicholasbrown suggestions work for my case. I was unable to connect to the Prefect server at 127.0.0.1:4200/graphql before allowing container to container communication.
